version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14.2

    working_directory: ~/eslint-config-barnardos

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package-lock.json" }}
            - v2-dependencies-

      - run:
          name: Update npm
          command: sudo npm install -g npm@latest

      - run:
          name: Check versions
          command: |
            node --version
            npm --version

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Run tests
          command: NODE_ENV=CI npm test
